@startuml document-overview

artifact "CDS FrPatient" as patient
artifact "CDS IHE CareTeam" as careteam #99FF99

artifact "CDS FrRelatedPerson" as cdsfrrelatedperson
artifact "CDS Organization" as cdsorganization
artifact "AS Practitioner" as aspractitioner
artifact "AS PractitionerRole" as aspractitionerrole

url of patient is [[StructureDefinition-cds-fr-patient.html]]
url of cdsfrrelatedperson is [[StructureDefinition-cds-fr-related-person.html]]
url of careteam is [[StructureDefinition-cds-ihe-careteam.html]]
url of cdsorganization is [[StructureDefinition-cds-organization.html]]

' ###########
' # Patient #
' ###########
patient <-- careteam : subject 0..1


' ############
' # careteam #
' ############
careteam --> cdsfrrelatedperson : participant[0..*].member
careteam --> cdsorganization : participant[0..*].member
careteam --> aspractitionerrole : participant[0..*].member

' ##################
' # frorganization #
' ##################
' asorganization --> asorganization : partof 1..*


' Dans le schéma initial, il y a d'autres relations qui n'ont pas été tracées : Lien entre orgaint et FrOrganization, Lien entre practitionerrole et organization.


' ####################
' # practitionerrole #
' ####################
aspractitionerrole -->  aspractitioner : practitioner 0..1

@enduml