# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.cds
canonical: https://interop.esante.gouv.fr/ig/fhir/cds 
name: CDS
title: Cercle De Soins
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 2.0.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: trial-use
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

dependencies:
  ans.fhir.fr.annuaire: 1.0.1
  hl7.fhir.fr.core: 2.0.1
  ans.fr.nos: latest

parameters:
    shownav: 'true'


pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Volume 1 - Etude fonctionnelle
    specifications_techniques.md:
        interaction_restful.md:
            title: Interactions RESTful
        interaction_transaction.md:
            title: Interactions transaction
        recherche_recuperation_cds.md:
            title: Recherche CDS
        correspondances_metier.md:
            title: Correspondances métier
    autres_ressources.md:
        title: Autres Ressources
        downloads.md:
            title: Téléchargements et usages

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: specifications_fonctionnelles.html
    Volume 2 - Détail des transactions:
        Interactions RESTful: interaction_restful.html
        Interactions transaction: interaction_transaction.html
        Recherche CDS: recherche_recuperation_cds.html
        Correspondances métier: correspondances_metier.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/

