name: Workflow Sushi Tests gitHubpages
on:
  workflow_call:
  push:
  workflow_dispatch:
jobs:
  run-sushi-tests_gitHubPages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ansforge/fhir-ig-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /home/runner/.fhir/packages:/root/.fhir/packages
    steps:
      - uses: actions/checkout@v3
        with:
          path: igSource
      - uses: ansforge/IG-workflows@docker-image-optimization
        with:
          repo_ig: "./igSource"
          github_page: "true"
          github_page_token: ${{ secrets.GITHUB_TOKEN }}
          bake: "false"
          validator_cli: "false"
          generate_testscript: "false"
          generate_plantuml: "false"
          container_mode: "true"
